# Generated by Django 4.1 on 2022-09-20 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_rate_user'),
        ('authentication', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('I', 'Invalid resource'), ('S', 'Spam or misleading'), ('M', 'Misinformation'), ('C', 'Captions issue')], max_length=1)),
                ('checked', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_related', to='courses.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
